Update create-jira-issue.yml

diff --git a/.github/workflows/create-jira-issue.yml b/.github/workflows/create-jira-issue.yml
--- a/.github/workflows/create-jira-issue.yml
+++ b/.github/workflows/create-jira-issue.yml
@@ -21,7 +21,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
-          ref: 'suyeon'  # suyeon 브랜치를 체크아웃
+          ref: 'suyeon'  # 'suyeon' 브랜치 체크아웃
 
       - name: Setup Git Config
         run: |
@@ -42,14 +42,17 @@ jobs:
           BRANCH_NAME="${PREFIX}-#${ISSUE_NUMBER}-${CLEAN_TITLE}"
           echo "Creating branch with name: $BRANCH_NAME"
           
-          # Display current branch and status
           git branch
           git status
           
           git checkout -b "$BRANCH_NAME"
-          echo "Checkout to $BRANCH_NAME completed."
+          if [ $? -ne 0 ]; then
+            echo "Checkout to $BRANCH_NAME failed."
+            exit 1
+          else
+            echo "Checkout to $BRANCH_NAME completed."
+          fi
 
-          # Detailed push attempt
           git push --set-upstream "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}" "$BRANCH_NAME" 2>&1 | tee push_output.txt
           if [ "${PIPESTATUS[0]}" != "0" ]; then
             echo "Failed to push branch $BRANCH_NAME"
